In [1]:
import numpy as np
import tensorflow as tf

In [5]:
class PowerLayer(tf.keras.layers.Layer):
  def __init__(self, power, dtype = tf.float64):
    super(PowerLayer, self).__init__(dtype = dtype)
    self.power  = power
  
  def call(self, inputs):
    return tf.math.pow(inputs, self.power)

In [17]:
class DiffLayer(tf.keras.layers.Layer):
  def __init__(self, func_layer, dtype = tf.float64):
    super(DiffLayer, self).__init__(dtype = dtype)
    self.func = func_layer
    self.inputs = None 
    
  def call(self, inputs):
    self.inputs = inputs
    with tf.GradientTape() as tape1:
      tape1.watch(self.inputs)
      df = tape1.gradient(self.func(self.inputs), self.inputs)
      #with tf.GradientTape() as tape2:
    return df

In [8]:
x = tf.constant([[1, 2], [3, 4]], dtype = tf.float64)

In [9]:
pl = PowerLayer(3)
pl(x)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  8.],
       [27., 64.]])>

In [18]:
dl = DiffLayer(pl)
dl2 = DiffLayer(dl)
dl2(x)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 6., 12.],
       [18., 24.]])>